version: '3.4'

services:
  assistant:
    image: ${DOCKER_REGISTRY-}assistantui
    environment:
      - ASPNETCORE_ENVIRONMENT=Docker
      - ASPNETCORE_HTTP_PORTS=5050
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '5050:5050'
